[package]
name = "kcgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
bpaf = "0.4.2"
enum-map = "2.1.0"
tree-sitter = "0.20.6"
tree-sitter-c = "0.20.1"
